# -*- coding: utf-8 -*-
"""Kaggle - Titanic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BDOjwTztAYsp3wnp0jy1qkzblCZPrg6e
"""

import pandas as pd
train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")
print(train.shape, test.shape)

train.head()

test.head()

y_pred = [0] * 418
print(len(y_pred))
print(y_pred)

submission = pd.DataFrame({
    'PassengerId': test['PassengerId'],
    'Survived': y_pred
})
submission.head()

# 저장하기
submission.to_csv('submission.csv', index=False)

